openapi: 3.0.0
info:
  version: 0.0-oas3
  title: RankBoardGame
  description: >-
    A simple service to get cpuinfo as an example of using swagger-2.0
    specification and codegen
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: Cloudmesh REST Service Example
  license:
    name: Apache
paths:
  /predict/{gamename}:
    get:
      tags:
        - PRED
      operationId: predict.prediction
      description: Gets the prediction of where a boardgame should rank.
      parameters:
        - in: path
          name: gamename
          required: true
          schema:
            type: array
            items:
              type: number
            minItems: 1
          style: simple
          explode: true
        - in: query
          name: metadata
          schema:
            type: boolean
      responses:
        '200':
          description: 'Predicted Rank'
servers:
  - url: 'http://localhost:8080/engr-222'
